name: Run Setup Script

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  bitcoin-setup:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository code

      - name: Cache Bitcoin Core
        id: cache-bitcoin
        uses: actions/cache@v3
        with:
          path: |
            bitcoin-28.0
            bitcoin-28.0-x86_64-linux-gnu.tar.gz
          key: bitcoin-core-28.0
          
      - name: Setup Bitcoin Core
        run: |
          if [ "${{ steps.cache-bitcoin.outputs.cache-hit }}" != 'true' ]; then
            wget https://bitcoincore.org/bin/bitcoin-core-28.0/bitcoin-28.0-x86_64-linux-gnu.tar.gz
            tar -xzvf bitcoin-28.0-x86_64-linux-gnu.tar.gz
          fi
          sudo bash .github/setup.sh

      - name: Start bitcoind in regtest mode
        run: |
          bitcoind -regtest -daemon
          echo "Waiting for bitcoind to be ready..."

          # Wait for bitcoind to start (max 30s)
          for i in {1..30}; do
            if bitcoin-cli -regtest getblockchaininfo > /dev/null 2>&1; then
              echo "✅ bitcoind is ready!"
              break
            fi
            echo "Still waiting for bitcoind..."
            sleep 1
          done

      - name: 01.sh - Verify Wallet Creation
        run: |
            chmod +x submission/01.sh
            WALLET=$(submission/01.sh)
            if [[ "$WALLET" == *"btrustwallet"* ]]; then
              echo "✅ Success: Wallet creation passed!"
            else
              echo "❌ Error: Wallet creation failed!"
              exit 1
            fi

      - name: 02.sh - Verify Raw Locked Transaction Generation
        run: |
          actual_sha() { printf '%s' "$1" | sha256sum | awk '{print $1}'; }
          chmod +x submission/02.sh
          TRANSACTION=$(submission/02.sh)
          EXPECTED_SHA=023c8d8214a5ed26059f814acac6ff42962bb6c272c0222c9c0fed26f4726666
          if [[ "$(actual_sha "$TRANSACTION")" == "$EXPECTED_SHA" ]]; then
            echo "✅ Success: Raw Locked Transaction generation passed!"
          else
            echo "❌ Error: Raw Locked Transaction generation failed!"
            exit 1
          fi
      
      - name: 03.sh - Verify Raw Transaction With Data
        run: |
          actual_sha() { printf '%s' "$1" | sha256sum | awk '{print $1}'; }
          chmod +x submission/03.sh
          TRANSACTION=$(submission/03.sh)
          EXPECTED_SHA=e67b481d27df392231fc0a9fbf9960c77e1bc3d4bac2ddde1c88754b80cb9b84
          if [[ "$(actual_sha "$TRANSACTION")" == "$EXPECTED_SHA" ]]; then
            echo "✅ Success: Raw Transaction With Data passed!"
          else
            echo "❌ Error: Raw Transaction With Data failed!"
            exit 1
          fi
          
      - name: 04.sh - Verify Locking Script
        run: |
          actual_sha() { printf '%s' "$1" | sha256sum | awk '{print $1}'; }
          chmod +x submission/04.sh
          SCRIPT=$(submission/04.sh)
          EXPECTED_SHA=65419b19dd8b1d9133799db41ed6a69c84837b2ddb891afefb9c68b13dc0924f
          if [[ "$(actual_sha "$SCRIPT")" == "$EXPECTED_SHA" ]]; then
            echo "✅ Success: Locking Script verification passed!"
          else
            echo "❌ Error: Locking Script verification failed!"
            exit 1
          fi
      
      - name: 05.sh - Verify UnLocking Script
        run: |
          actual_sha() { printf '%s' "$1" | sha256sum | awk '{print $1}'; }
          chmod +x submission/05.sh
          SCRIPT=$(submission/05.sh)
          EXPECTED_SHA=40d6d968d67bba838c51d094e77d93a4ec88db441d170a8d4ed5d59b7d8072c8
          if [[ "$(actual_sha "$SCRIPT")" == "$EXPECTED_SHA" ]]; then
            echo "✅ Success: UnLocking Script verification passed!"
          else
            echo "❌ Error: UnLocking Script verification failed!"
            exit 1
          fi

      - name: 06.sh - Verify Witness Signature
        run: |
          actual_sha() { printf '%s' "$1" | sha256sum | awk '{print $1}'; }
          chmod +x submission/06.sh
          SIGNATURE=$(submission/06.sh)
          EXPECTED_SHA=49b67ed3b9a875669b804b2bd687558e5072dd2c6e8baba0221095daa118294f
          if [[ "$(actual_sha "$SIGNATURE")" == "$EXPECTED_SHA" ]]; then
            echo "✅ Success: Witness Signature verification passed!"
          else
            echo "❌ Error: Witness Signature verification failed!"
            exit 1
          fi

      - name: 07.sh - Verify Public Key
        run: |
          actual_sha() { printf '%s' "$1" | sha256sum | awk '{print $1}'; }
          chmod +x submission/07.sh
          PUBKEY=$(submission/07.sh)
          EXPECTED_SHA=c5a98d0d78641209ff0ed6cda76efa2ab289be76cad11f5a3c04e29cc3c73b0f
          if [[ "$(actual_sha "$PUBKEY")" == "$EXPECTED_SHA" ]]; then
            echo "✅ Success: Witness Public Key verification passed!"
          else
            echo "❌ Error: Witness Public Key verification failed!"
            exit 1
          fi